import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

function isSequence(part) {
  let pattern = /E[\w\d]+/g
  let regex = new RegExp(pattern)
  return regex.test(part['Complete Number'])
}

const store = new Vuex.Store({
    state: {
        parts: [
            {
              "Item": "54",
              "Export Item": "4",
              "Complete Number": "14923-E1023",
              "Description": "SEQ. CONTAINER",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "",
              "LengthDec": "",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "NA",
              "Mitre": "",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4",
              "Export Item": "4.4",
              "Complete Number": "14923-ACK7102",
              "Description": "ANCHOR KIT",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "9 1/16",
              "LengthDec": "9.0551",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "URL": "/static/ACK7102.dwg.pdf"
            },
            {
              "Item": "54.4.7",
              "Export Item": "4.4.7",
              "Complete Number": "14923-ACA2002",
              "Description": "ANCHOR BRACKET",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "9 1/16",
              "LengthDec": "9.0551",
              "EXTRUSION NO": "ACS100479",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.11",
              "Export Item": "4.4.11",
              "Complete Number": "14923-ACF2003",
              "Description": "ANCHOR FEMALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "7 3/32",
              "LengthDec": "7.0866",
              "EXTRUSION NO": "ACS100855",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.12",
              "Export Item": "4.4.12",
              "Complete Number": "14923-ACF2004",
              "Description": "ANCHOR FEMALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "7 3/32",
              "LengthDec": "7.0866",
              "EXTRUSION NO": "ACS100855",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.9",
              "Export Item": "4.4.9",
              "Complete Number": "14923-ACM2001",
              "Description": "ANCHOR MALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "4 19/32",
              "LengthDec": "4.6063",
              "EXTRUSION NO": "ACS100466",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.10",
              "Export Item": "4.4.10",
              "Complete Number": "14923-ACM2002",
              "Description": "ANCHOR MALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "4 19/32",
              "LengthDec": "4.6063",
              "EXTRUSION NO": "ACS100466",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.8",
              "Export Item": "4.4.8",
              "Complete Number": "14923-ACW2001",
              "Description": "ANCHOR WASHER",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "2",
              "LengthDec": "2",
              "EXTRUSION NO": "ACS100021",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.5",
              "Export Item": "4.4.5",
              "Complete Number": "14923-FSR1010",
              "Description": "1/4-14x1.5 HWH Tek",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "1 1/2",
              "LengthDec": "1.5",
              "EXTRUSION NO": "NA",
              "FINISH": "XYLAN 410SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.1",
              "Export Item": "4.4.1",
              "Complete Number": "14923-FSR1033",
              "Description": "1/2-13x2.5 HEX BOLT",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "2 1/2",
              "LengthDec": "2.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED GR5",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.4",
              "Export Item": "4.4.4",
              "Complete Number": "14923-FSR1034",
              "Description": "1/2-13 Hex. Nut",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED GR5",
              "Part Type": "y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.3",
              "Export Item": "4.4.3",
              "Complete Number": "14923-FSR1035",
              "Description": "1/2 LOCK WASHER",
              "Unit QTY": "1",
              "QTY": "8",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED MILD STEEL",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.13",
              "Export Item": "4.4.13",
              "Complete Number": "14923-FSR1178",
              "Description": "1/2-13x3.5 Hex Bolt",
              "Unit QTY": "1",
              "QTY": "6",
              "Length": "3 1/2",
              "LengthDec": "3.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED GR5",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.6",
              "Export Item": "4.4.6",
              "Complete Number": "14923-FSR1404",
              "Description": "1/2-13x2 skt Set Scr",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "2",
              "LengthDec": "2",
              "EXTRUSION NO": "NA",
              "FINISH": "BLACK OXIDE ALLOY",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.4.2",
              "Export Item": "4.4.2",
              "Complete Number": "14923-FSR1503",
              "Description": "1/2 WASHER",
              "Unit QTY": "1",
              "QTY": "8",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED MILD STEEL",
              "Part Type": "y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14",
              "Export Item": "4.14",
              "Complete Number": "14923-ACK7111",
              "Description": "ANCHOR KIT",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "9 1/16",
              "LengthDec": "9.0551",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "URL": "/static/ACK7111.dwg.pdf"
            },
            {
              "Item": "54.14.6",
              "Export Item": "4.14.6",
              "Complete Number": "14923-ACA2002",
              "Description": "ANCHOR BRACKET",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "9 1/16",
              "LengthDec": "9.0551",
              "EXTRUSION NO": "ACS100479",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.10",
              "Export Item": "4.14.10",
              "Complete Number": "14923-ACF2003",
              "Description": "ANCHOR FEMALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "7 3/32",
              "LengthDec": "7.0866",
              "EXTRUSION NO": "ACS100855",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.11",
              "Export Item": "4.14.11",
              "Complete Number": "14923-ACF2004",
              "Description": "ANCHOR FEMALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "7 3/32",
              "LengthDec": "7.0866",
              "EXTRUSION NO": "ACS100855",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.8",
              "Export Item": "4.14.8",
              "Complete Number": "14923-ACM2001",
              "Description": "ANCHOR MALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "4 19/32",
              "LengthDec": "4.6063",
              "EXTRUSION NO": "ACS100466",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.9",
              "Export Item": "4.14.9",
              "Complete Number": "14923-ACM2002",
              "Description": "ANCHOR MALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "4 19/32",
              "LengthDec": "4.6063",
              "EXTRUSION NO": "ACS100466",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.7",
              "Export Item": "4.14.7",
              "Complete Number": "14923-ACW2001",
              "Description": "ANCHOR WASHER",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "2",
              "LengthDec": "2",
              "EXTRUSION NO": "ACS100021",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.5",
              "Export Item": "4.14.5",
              "Complete Number": "14923-FSR1010",
              "Description": "1/4-14x1.5 HWH Tek",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "1 1/2",
              "LengthDec": "1.5",
              "EXTRUSION NO": "NA",
              "FINISH": "XYLAN 410SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.1",
              "Export Item": "4.14.1",
              "Complete Number": "14923-FSR1033",
              "Description": "1/2-13x2.5 HEX BOLT",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "2 1/2",
              "LengthDec": "2.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED GR5",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.4",
              "Export Item": "4.14.4",
              "Complete Number": "14923-FSR1034",
              "Description": "1/2-13 Hex. Nut",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED GR5",
              "Part Type": "y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.3",
              "Export Item": "4.14.3",
              "Complete Number": "14923-FSR1035",
              "Description": "1/2 LOCK WASHER",
              "Unit QTY": "1",
              "QTY": "8",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED MILD STEEL",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.12",
              "Export Item": "4.14.12",
              "Complete Number": "14923-FSR1178",
              "Description": "1/2-13x3.5 Hex Bolt",
              "Unit QTY": "1",
              "QTY": "6",
              "Length": "3 1/2",
              "LengthDec": "3.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED GR5",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.14.2",
              "Export Item": "4.14.2",
              "Complete Number": "14923-FSR1503",
              "Description": "1/2 WASHER",
              "Unit QTY": "1",
              "QTY": "8",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "ZINC PLATED MILD STEEL",
              "Part Type": "y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.12",
              "Export Item": "4.12",
              "Complete Number": "14923-BSA2013",
              "Description": "BREAK SHAPE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "4 7/8",
              "LengthDec": "4.875",
              "EXTRUSION NO": "ALUM SHEET, 12 Ga. (.081in)",
              "FINISH": "CLEAR ANODIZED",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "URL": "/static/BSA2013.dwg.pdf"
            },
            {
              "Item": "54.13",
              "Export Item": "4.13",
              "Complete Number": "14923-BSA2018",
              "Description": "BREAK SHAPE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "4 7/8",
              "LengthDec": "4.875",
              "EXTRUSION NO": "ALUM SHEET, 12 Ga. (.081in)",
              "FINISH": "CLEAR ANODIZED",
              "Part Type": "B",
              "Mitre": "Y",
              "Level": "5",
              "URL": "/static/BSA2018.dwg.pdf"
            },
            {
              "Item": "54.9",
              "Export Item": "4.9",
              "Complete Number": "14923-BSP2002",
              "Description": "STOOL TRIM SPLICE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "6 1/4",
              "LengthDec": "6.25",
              "EXTRUSION NO": "ALUM SHEET, 20 Ga. (.032in)",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "URL": "/static/BSP2002.dwg.pdf"
            },
            {
              "Item": "54.10",
              "Export Item": "4.10",
              "Complete Number": "14923-BSP2007",
              "Description": "STOOL TRIM SPLICE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "2",
              "LengthDec": "2",
              "EXTRUSION NO": "ALUM SHEET, 20 Ga. (.032in)",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "URL": "/static/BSP2007.dwg.pdf"
            },
            {
              "Item": "54.1",
              "Export Item": "4.1",
              "Complete Number": "14923-E1023",
              "Description": "SEQ. BLOCK",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "",
              "LengthDec": "",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "NA",
              "Mitre": "",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11",
              "Export Item": "4.11",
              "Complete Number": "14923-FRM1053",
              "Description": "FRAME, 8D666",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "89 5/8 x 203 1/4",
              "LengthDec": "89.6113 x 203.2524",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "M",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.13",
              "Export Item": "4.11.13",
              "Complete Number": "14923-BPN2015",
              "Description": "BACK PAN",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "77 9/16 x 38 1/8",
              "LengthDec": "77.5758 x 38.125",
              "EXTRUSION NO": "STEEL SHEET, 20 Ga. (.04in), GMS",
              "FINISH": "GALVANIZED",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.21",
              "Export Item": "4.11.21",
              "Complete Number": "14923-BPN2023",
              "Description": "BACK PAN",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "77 9/16 x 41 31/32",
              "LengthDec": "77.5758 x 41.9636",
              "EXTRUSION NO": "STEEL SHEET, 20 Ga. (.04in), GMS",
              "FINISH": "GALVANIZED",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.18",
              "Export Item": "4.11.18",
              "Complete Number": "14923-GV11035",
              "Description": "GLASS VISION",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "86 23/32 x 196 1/32",
              "LengthDec": "86.7051 x 196.0394",
              "EXTRUSION NO": "GV1",
              "FINISH": "NA",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.8",
              "Export Item": "4.11.8",
              "Complete Number": "14923-HPP2003",
              "Description": "HORZ PRESS PLATE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "86 3/4",
              "LengthDec": "86.7500",
              "EXTRUSION NO": "ACS100764",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.6",
              "Export Item": "4.11.6",
              "Complete Number": "14923-HZF2003",
              "Description": "HORZ FILLER",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "82 5/8",
              "LengthDec": "82.625",
              "EXTRUSION NO": "ACS100817",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.19",
              "Export Item": "4.11.19",
              "Complete Number": "14923-HZH2025",
              "Description": "HORZ HEAD",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "82 25/32",
              "LengthDec": "82.7892",
              "EXTRUSION NO": "ACS100839",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.9",
              "Export Item": "4.11.9",
              "Complete Number": "14923-HZH7121",
              "Description": "HORZ HEAD, SUB-ASSEMBLY",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "88 3/8",
              "LengthDec": "88.3750",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.9.1",
              "Export Item": "4.11.9.1",
              "Complete Number": "14923-FSR1488",
              "Description": "10-24x0.5 Pan sq MS",
              "Unit QTY": "1",
              "QTY": "12",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.9.3",
              "Export Item": "4.11.9.3",
              "Complete Number": "14923-HFG2022",
              "Description": "HORZ FINGER",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "88 3/8",
              "LengthDec": "88.375",
              "EXTRUSION NO": "ACS100807",
              "FINISH": "ANODIC BLACK YN205E",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.9.2",
              "Export Item": "4.11.9.2",
              "Complete Number": "14923-HZH2021",
              "Description": "HORZ HEAD",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "86 1/16",
              "LengthDec": "86.0483",
              "EXTRUSION NO": "ACS100804",
              "FINISH": "PRE-ANODIZED",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.5",
              "Export Item": "4.11.5",
              "Complete Number": "14923-HZM2003",
              "Description": "HORZ MAIN",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "82 25/32",
              "LengthDec": "82.781",
              "EXTRUSION NO": "ACS100816",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.16",
              "Export Item": "4.11.16",
              "Complete Number": "14923-HZS7130",
              "Description": "HORZ SILL, SUB-ASSEMBLY",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "88 13/16",
              "LengthDec": "88.8123",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.16.1",
              "Export Item": "4.11.16.1",
              "Complete Number": "14923-FSR1653",
              "Description": "10-16x0.75 Pan sq Tek",
              "Unit QTY": "1",
              "QTY": "10",
              "Length": "3/4",
              "LengthDec": "0.75",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.16.3",
              "Export Item": "4.11.16.3",
              "Complete Number": "14923-HNC2003",
              "Description": "HORZ NECK",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "88 13/16",
              "LengthDec": "88.8123",
              "EXTRUSION NO": "ACS800087",
              "FINISH": "PRE-ANODIZED",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.16.2",
              "Export Item": "4.11.16.2",
              "Complete Number": "14923-HZS2029",
              "Description": "HORZ SILL",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "82 25/32",
              "LengthDec": "82.7892",
              "EXTRUSION NO": "ACS100856",
              "FINISH": "PRE-ANODIZED",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.16.4",
              "Export Item": "4.11.16.4",
              "Complete Number": "14923-STL2005",
              "Description": "REINFORCING",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "79 3/8",
              "LengthDec": "79.3649",
              "EXTRUSION NO": "STEEL FLAT BAR, 5/8 THK.",
              "FINISH": "GALVANIZED",
              "Part Type": "B",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.3",
              "Export Item": "4.11.3",
              "Complete Number": "14923-LGL2003",
              "Description": "LUG LIFTING",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "7 7/8",
              "LengthDec": "7.875",
              "EXTRUSION NO": "ACS100805",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.10",
              "Export Item": "4.11.10",
              "Complete Number": "14923-LGL2005",
              "Description": "LUG LIFTING",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "12 11/16",
              "LengthDec": "12.7005",
              "EXTRUSION NO": "ACS100805",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.1",
              "Export Item": "4.11.1",
              "Complete Number": "14923-LGS2001",
              "Description": "LUG SLIDER",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "6",
              "LengthDec": "6",
              "EXTRUSION NO": "TB492",
              "FINISH": "BLACK",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.4",
              "Export Item": "4.11.4",
              "Complete Number": "14923-LGS2002",
              "Description": "LUG SLIDER",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "6 3/4",
              "LengthDec": "6.75",
              "EXTRUSION NO": "TB492",
              "FINISH": "BLACK",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15",
              "Export Item": "4.11.15",
              "Complete Number": "14923-MCM7103",
              "Description": "MULL COR MALE, SUB-ASSEMBLY",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "198 19/32",
              "LengthDec": "198.6000",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.8",
              "Export Item": "4.11.15.8",
              "Complete Number": "14923-ABC2004",
              "Description": "ANTI-BUCKLE CLIP",
              "Unit QTY": "1",
              "QTY": "3",
              "Length": "4",
              "LengthDec": "4",
              "EXTRUSION NO": "ACS100057",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.4",
              "Export Item": "4.11.15.4",
              "Complete Number": "14923-ACB2002",
              "Description": "ANCHOR BACKUP",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "7 3/32",
              "LengthDec": "7.0866",
              "EXTRUSION NO": "ACS100726",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.7",
              "Export Item": "4.11.15.7",
              "Complete Number": "14923-FSR1043",
              "Description": "12-24x0.5 PAN SQ MS",
              "Unit QTY": "1",
              "QTY": "26",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.1",
              "Export Item": "4.11.15.1",
              "Complete Number": "14923-FSR1109",
              "Description": "1/4-20x0.75 Pan sq MS",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "3/4",
              "LengthDec": "0.75",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.6",
              "Export Item": "4.11.15.6",
              "Complete Number": "14923-FSR1223",
              "Description": "#12-14x1 FLAT SQ TEK",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "1",
              "LengthDec": "1",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.2",
              "Export Item": "4.11.15.2",
              "Complete Number": "14923-FSR1280",
              "Description": "1/4 WASHER",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "1/4",
              "LengthDec": "0.25",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.5",
              "Export Item": "4.11.15.5",
              "Complete Number": "14923-FSR1390",
              "Description": "8x0.25 Pan ph 'F'",
              "Unit QTY": "1",
              "QTY": "6",
              "Length": "1/4",
              "LengthDec": "0.25",
              "EXTRUSION NO": "NA",
              "FINISH": "Xylan 410SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.9",
              "Export Item": "4.11.15.9",
              "Complete Number": "14923-MCM2003",
              "Description": "MULL COR MALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "198 19/32",
              "LengthDec": "198.6000",
              "EXTRUSION NO": "ACS100818",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.3",
              "Export Item": "4.11.15.3",
              "Complete Number": "14923-SPP2001",
              "Description": "SPACER, PVC",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "1/4\"∅ PVC TUBE SPACER",
              "FINISH": "GRAY",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.15.10",
              "Export Item": "4.11.15.10",
              "Complete Number": "14923-VFG2009",
              "Description": "VERT FINGER",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "196 7/32",
              "LengthDec": "196.225",
              "EXTRUSION NO": "ACS800079",
              "FINISH": "ANODIC BLACK YN205E",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14",
              "Export Item": "4.11.14",
              "Complete Number": "14923-MLF7109",
              "Description": "MULL FEMALE, SUB-ASSEMBLY",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "198 19/32",
              "LengthDec": "198.6000",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.3",
              "Export Item": "4.11.14.3",
              "Complete Number": "14923-ABC2002",
              "Description": "ANTI-BUCKLE CLIP, FEMALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "4",
              "LengthDec": "4",
              "EXTRUSION NO": "ACS100685",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.5",
              "Export Item": "4.11.14.5",
              "Complete Number": "14923-ABC2003",
              "Description": "ANTI-BUCKLE CLIP",
              "Unit QTY": "1",
              "QTY": "3",
              "Length": "4",
              "LengthDec": "4",
              "EXTRUSION NO": "ACS100553",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.10",
              "Export Item": "4.11.14.10",
              "Complete Number": "14923-ABC2006",
              "Description": "ANTI-BUCKLING CLIP, FEMALE",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "6",
              "LengthDec": "6",
              "EXTRUSION NO": "ACS100827",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.1",
              "Export Item": "4.11.14.1",
              "Complete Number": "14923-ACB2001",
              "Description": "ANCHOR BACKUP",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "7 3/32",
              "LengthDec": "7.0866",
              "EXTRUSION NO": "ACS100543",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.7",
              "Export Item": "4.11.14.7",
              "Complete Number": "14923-FSR1109",
              "Description": "1/4-20x0.75 Pan sq MS",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "3/4",
              "LengthDec": "0.75",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.4",
              "Export Item": "4.11.14.4",
              "Complete Number": "14923-FSR1223",
              "Description": "#12-14x1 FLAT SQ TEK",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "1",
              "LengthDec": "1",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.8",
              "Export Item": "4.11.14.8",
              "Complete Number": "14923-FSR1280",
              "Description": "1/4 WASHER",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "1/4",
              "LengthDec": "0.25",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.2",
              "Export Item": "4.11.14.2",
              "Complete Number": "14923-FSR1599",
              "Description": "10-16x0.3125 Pan ph 'B'",
              "Unit QTY": "1",
              "QTY": "10",
              "Length": "5/16",
              "LengthDec": "0.313",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.9",
              "Export Item": "4.11.14.9",
              "Complete Number": "14923-MLF2009",
              "Description": "MULL FEMALE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "198 19/32",
              "LengthDec": "198.6000",
              "EXTRUSION NO": "ACS100802",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.14.6",
              "Export Item": "4.11.14.6",
              "Complete Number": "14923-SPP2001",
              "Description": "SPACER, PVC",
              "Unit QTY": "1",
              "QTY": "4",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "1/4\"∅ PVC TUBE SPACER",
              "FINISH": "GRAY",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.22",
              "Export Item": "4.11.22",
              "Complete Number": "14923-SB454",
              "Description": "SETTING BLOCK",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "6",
              "LengthDec": "6",
              "EXTRUSION NO": "SB454",
              "FINISH": "BLACK",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.17",
              "Export Item": "4.11.17",
              "Complete Number": "14923-SBC2001",
              "Description": "SET BLOCK CHAIR",
              "Unit QTY": "1",
              "QTY": "2",
              "Length": "6",
              "LengthDec": "6",
              "EXTRUSION NO": "ACS100806",
              "FINISH": "PRE-ANODIZED",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.7",
              "Export Item": "4.11.7",
              "Complete Number": "14923-SHB7103",
              "Description": "SHADOW BOX, SUB-ASSEMBLY",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "80 13/32 x 38 1/2",
              "LengthDec": "80.407 x 38.4926",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.7.1",
              "Export Item": "4.11.7.1",
              "Complete Number": "14923-FSR1509",
              "Description": "5/32 X.625 BLIND RIVET",
              "Unit QTY": "1",
              "QTY": "11",
              "Length": "5/8",
              "LengthDec": "0.625",
              "EXTRUSION NO": "NA",
              "FINISH": "ALUMINUM",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.7.2",
              "Export Item": "4.11.7.2",
              "Complete Number": "14923-SHB2003",
              "Description": "SHADOW BOX",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "80 13/32 x 38 7/16",
              "LengthDec": "80.407 x 38.4375",
              "EXTRUSION NO": "ALUM SHEET, 8 Ga. (.125in)",
              "FINISH": "BM SWEATSHIRT GRAY",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.7.3",
              "Export Item": "4.11.7.3",
              "Complete Number": "14923-SPP2006",
              "Description": "SPACER, PVC",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "79 29/32",
              "LengthDec": "79.907",
              "EXTRUSION NO": "PVC SHEET, 1/8 THK.",
              "FINISH": "ANY",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.7.4",
              "Export Item": "4.11.7.4",
              "Complete Number": "14923-TRM2006",
              "Description": "TRIM",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "79 11/32",
              "LengthDec": "79.344",
              "EXTRUSION NO": "ACS100749",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.20",
              "Export Item": "4.11.20",
              "Complete Number": "14923-SHB7115",
              "Description": "SHADOW BOX, SUB-ASSEMBLY",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "80 13/32 x 44 13/16",
              "LengthDec": "80.407 x 44.8034",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.20.1",
              "Export Item": "4.11.20.1",
              "Complete Number": "14923-FSR1509",
              "Description": "5/32 X.625 BLIND RIVET",
              "Unit QTY": "1",
              "QTY": "11",
              "Length": "5/8",
              "LengthDec": "0.625",
              "EXTRUSION NO": "NA",
              "FINISH": "ALUMINUM",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.20.4",
              "Export Item": "4.11.20.4",
              "Complete Number": "14923-SHB2014",
              "Description": "SHADOW BOX",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "80 13/32 x 44 3/4",
              "LengthDec": "80.407 x 44.7483",
              "EXTRUSION NO": "ALUM SHEET, 8 Ga. (.125in)",
              "FINISH": "BM SWEATSHIRT GRAY",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.20.2",
              "Export Item": "4.11.20.2",
              "Complete Number": "14923-SPP2006",
              "Description": "SPACER, PVC",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "79 29/32",
              "LengthDec": "79.907",
              "EXTRUSION NO": "PVC SHEET, 1/8 THK.",
              "FINISH": "ANY",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.20.3",
              "Export Item": "4.11.20.3",
              "Complete Number": "14923-TRM2006",
              "Description": "TRIM",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "79 11/32",
              "LengthDec": "79.344",
              "EXTRUSION NO": "ACS100749",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.11",
              "Export Item": "4.11.11",
              "Complete Number": "14923-SPP2011",
              "Description": "SPACER, PVC",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "5",
              "LengthDec": "5",
              "EXTRUSION NO": "PVC SHEET, 1/16 THK.",
              "FINISH": "ANY",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.2",
              "Export Item": "4.11.2",
              "Complete Number": "14923-THS2003",
              "Description": "THERMAL SHIELD",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "84 5/8",
              "LengthDec": "84.625",
              "EXTRUSION NO": "TS423",
              "FINISH": "BLACK",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.11.12",
              "Export Item": "4.11.12",
              "Complete Number": "14923-WWA2001",
              "Description": "WINDOW ANCHOR",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "7 3/4",
              "LengthDec": "7.7392",
              "EXTRUSION NO": "NA",
              "FINISH": "MILL",
              "Part Type": "B",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.16",
              "Export Item": "4.16",
              "Complete Number": "14923-FSR1124",
              "Description": "10-16x1 Pan sq Tek",
              "Unit QTY": "1",
              "QTY": "11",
              "Length": "1",
              "LengthDec": "1",
              "EXTRUSION NO": "NA",
              "FINISH": "XYLAN 410SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.8",
              "Export Item": "4.8",
              "Complete Number": "14923-FSR1146",
              "Description": "8x0.5 Flat UC sq 'AB'",
              "Unit QTY": "1",
              "QTY": "3",
              "Length": "1/2",
              "LengthDec": "0.5",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.7",
              "Export Item": "4.7",
              "Complete Number": "14923-FSR1653",
              "Description": "10-16x0.75 Pan sq Tek",
              "Unit QTY": "1",
              "QTY": "10",
              "Length": "3/4",
              "LengthDec": "0.75",
              "EXTRUSION NO": "NA",
              "FINISH": "18.8SS",
              "Part Type": "Y",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.3",
              "Export Item": "4.3",
              "Complete Number": "14923-HCP2003",
              "Description": "HORZ CAP",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "92 3/4",
              "LengthDec": "92.7465",
              "EXTRUSION NO": "ACS100766",
              "FINISH": "CLEAR ANODIZED",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.15",
              "Export Item": "4.15",
              "Complete Number": "14923-HZF7107",
              "Description": "HORZ FILLER, SUB-ASSEMBLY",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "88 3/8",
              "LengthDec": "88.3840",
              "EXTRUSION NO": "NA",
              "FINISH": "NA",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.15.1",
              "Export Item": "4.15.1",
              "Complete Number": "14923-HZF2013",
              "Description": "HORZ FILLER",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "88 3/8",
              "LengthDec": "88.384",
              "EXTRUSION NO": "ACS100858",
              "FINISH": "CLEAR ANODIZED",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.15.2",
              "Export Item": "4.15.2",
              "Complete Number": "14923-THB2004",
              "Description": "THERMAL BREAK",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "79",
              "LengthDec": "79",
              "EXTRUSION NO": "TB486",
              "FINISH": "BLACK",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.5",
              "Export Item": "4.5",
              "Complete Number": "14923-TRM2503",
              "Description": "STOOL TRIM",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "79 9/16",
              "LengthDec": "79.548",
              "EXTRUSION NO": "ACS100836",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "A",
              "Mitre": "Y",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.6",
              "Export Item": "4.6",
              "Complete Number": "14923-TRM2504",
              "Description": "STOOL TRIM CLOSURE",
              "Unit QTY": "1",
              "QTY": "1",
              "Length": "74 9/16",
              "LengthDec": "74.565",
              "EXTRUSION NO": "ACS100869",
              "FINISH": "ANODIC ICE YW201E",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            },
            {
              "Item": "54.2",
              "Export Item": "4.2",
              "Complete Number": "14923-TRS2001",
              "Description": "STOOL TRIM SUPPORT",
              "Unit QTY": "1",
              "QTY": "3",
              "Length": "4",
              "LengthDec": "4",
              "EXTRUSION NO": "ACS100377",
              "FINISH": "MILL",
              "Part Type": "A",
              "Mitre": "N",
              "Level": "5",
              "field14": ""
            }
          ]
    },
    mutations: {

    },
    actions: {

    },
    getters: {
        getDescriptions: state => {
          return state.parts.map(x => x.Description)
        },
        getParts: state => {
          
          return state.parts.filter(part => !isSequence(part))
        },
        getPart: state => partName => {
          return state.parts.find(part => part['Complete Number'].search(partName) >= 0)
        },
        getPartsInSequence: state => sequence => {
          let item = state.parts.find(part => part['Complete Number'] == sequence).Item
          let itemLength = item.length
          return state.parts.filter(part => part.Item.substring(0, itemLength) == item && ! isSequence(part))
        },
        getSequence: state => sequence => {
          return state.parts.find(part => part['Complete Number'].search(sequence) >= 0)
        },
        getSequences: state => {
          return state.parts.filter(part => isSequence(part) && part['Export Item'].indexOf('.') < 0)
        },
        foundIn: state => part => {
          let items = state.parts.filter(p => p['Complete Number'].split('-')[1] == part.split('-')[1]).map(x => x.Item)
          let sequences = items.map(item => {
            let seq = item.split('.')[0]
            return state.parts.find(p => p.Item == seq)
          })
          return sequences
        }
    }
})

export default store